export {default as Loader} from './Loader'
export {default as Footer} from './Footer'
export {default as NavBar} from './NavBar'
export {default as Transaction} from './Transaction'
export {default as Welcome} from './Welcome'
export {default as Services} from './Services'